# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermessage',
            name='id',
        ),
        migrations.AlterField(
            model_name='registermessage',
            name='phone',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
