# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20170424_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermessage',
            name='campus',
            field=models.CharField(choices=[('s', '\u6c99\u6cb3\u6821\u533a'), ('q', '\u6e05\u6c34\u6cb3\u6821\u533a')], default='q', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registermessage',
            name='grade',
            field=models.CharField(choices=[('f', '\u5927\u4e00'), ('sf', '\u5927\u4e8c'), ('j', '\u5927\u4e09'), ('sn', '\u5927\u56db'), ('m', '\u7814\u7a76\u751f')], default='f', max_length=2, verbose_name='\u5e74\u7ea7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registermessage',
            name='language',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='registermessage',
            name='major',
            field=models.CharField(default='computer', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registermessage',
            name='qq',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
