# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20170426_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermessage',
            name='grade',
            field=models.CharField(blank=True, choices=[('f', '\u5927\u4e00'), ('sf', '\u5927\u4e8c'), ('j', '\u5927\u4e09'), ('sn', '\u5927\u56db'), ('m', '\u7814\u7a76\u751f')], max_length=2, null=True, verbose_name='\u5e74\u7ea7'),
        ),
        migrations.AlterField(
            model_name='registermessage',
            name='major',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
