# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_winner'),
    ]

    operations = [

        migrations.AddField(
            model_name='winner',
            name='prize',
            field=models.CharField(choices=[('1', '\u7b2c\u4e00\u540d'), ('2', '\u7b2c\u4e8c\u540d'), ('3', '\u7b2c\u4e09\u540d'), ('x', '\u6548\u7387\u5956')], default='x', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='winner',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
