# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20170516_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
