# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='\u7535\u8bdd')),
                ('company', models.CharField(max_length=40, verbose_name='\u516c\u53f8')),
                ('jobtitle', models.CharField(max_length=15, verbose_name='\u804c\u4f4d')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='\u90ae\u7bb1')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u65f6\u95f4')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
